version: '3'
services:
  #MOSS Mysql数据库初使化
  moss-db-init:
    image: mysql:5.7
    command: /init-db.sh
    networks:
      - sc-net
    volumes:
      - ./moss/mysql:/sql
      - ./init-db.sh:/init-db.sh
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234

  #Moss管理中心
  moss:
    image: kylinzhang/moss-web:latest
    container_name: moss
    #restart: always
    networks:
      - sc-net
    ports:
      - 8086:8086
    env_file: .env
    environment:
      TZ: Asia/Shanghai

networks:
  sc-net:
    external: false